### PR TITLE
Enable Better Logging for ES Bulk Operations

### PR DESCRIPTION
**Pull request by aterreno**
Hey @matrus2 I've done a few bits here: 

- update libraries to latest
- docker-compose to run easily the same version of ES library in the code + changed readme to do that

... More importantly 

I've put back the detailed logging of ES bulk operations as we are struggling to pinpoint when an error happens (I did push this few years ago already but then we did skip the feature) 

Can you please let me know if you like this change or where I can improve it? 

Thanks a lot

### CODE REVIEW

**Comment by matrus2** [comment]
Hi, Thank you for PR. I think we are blocked:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: dynamodb-stream-elasticsearch@3.0.2
npm ERR! Found: @elastic/elasticsearch@7.13.0
npm ERR! node_modules/@elastic/elasticsearch
npm ERR!   @elastic/elasticsearch@"7.13.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @elastic/elasticsearch@">=5.6.16 <=7.9.1" from @acuris/aws-es-connection@2.2.0
npm ERR! node_modules/@acuris/aws-es-connection
npm ERR!   @acuris/aws-es-connection@"2.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/matrus2/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matrus2/.npm/_logs/2021-07-16T14_17_37_020Z-debug.log
```

The issue already raised: 
https://github.com/mergermarket/acuris-aws-es-connection/issues/56

I going to change travis config to execute tests on each PR.

**Comment by aterreno** [comment]
@matrus2 strange - I did run the tests locally - I've submitted a PR over there and hopefully we'll get a new release soon, otherwise I can undo the ES version changes.

**Comment by aterreno** [comment]
Yes I was thinking that as well

**Comment by aterreno** [comment]
Hey @matrus2, I've 'ported' the library we depended on, that meant: 

- changing code from ts to js 
- changing tests from ts+jest to js+chai

Now, the library itself was testing a bit 'brutally' using a real ES cluster, I've changed the docker-compose.yaml file to run a localstack (https://github.com/localstack/localstack) 

The setup to run that test is still a bit convoluted (start docker, install pip for the localstack cli utility, create an es domain on localstack, ..) and there is also an issue with localstack (it doesn't run ok on macs m1). 

let me know what you think. in a way we are in a better position than before: 
- we don't rely on a super tiny 3rd party library with a maintainer that doesn't respond promptly 
- we can test locally and I am sure we can automate in CI if we want 

Thoughts?

**Comment by matrus2** [comment]
I have some thoughts of how to improve a bit, but to not to keep you waiting I will merge and apply it independently, but shortly :)

Thanks for the PR

**Pull request merged**
