### PR TITLE
Accept complex data types in a DynamoDB document fields

### PR DESCRIPTION
**Pull request by alecdotico**
A DynamoDB document can contain complex data types like DynamoDB custom Sets or inner objects. Extend the DynamoDB record conversion to adapt them to a Elasticsearch document. That covers:
- String Sets (SS).
- Number Sets (NS).
- Objects, also called Maps (M).

DynamoDB Streams stringify complex objects in order to be serializable. Simpler data types like an array of strings have a special format too (value.values).

### CODE REVIEW

**Comment by matrus2** [comment]
You raised very good issue, but this code doesn't solve it entirely.
To see what I mean take the following input data:

```const veryComplexData = {
  Records: [
    {
      eventID: 'bc87af2e29e12f293d5e4f5d5d7e2e0a',
      eventName: 'MODIFY',
      eventVersion: '1.1',
      eventSource: 'aws:dynamodb',
      awsRegion: 'eu-central-1',
      dynamodb: {
        ApproximateCreationDateTime: 1548519006,
        Keys: {
          id: {
            S: '12'
          }
        },
        NewImage: {
          number: {
            N: '123'
          },
          nbset: {
            NS: ['12']
          },
          data: {
            M: {
              '12': {
                BS: ['YWRzYQ==', 'dGVzdCE=']
              },
              first: {
                S: 'first'
              }
            }
          },
          strset: {
            SS: ['asd', 'asdasd']
          },
          adress: {
            M: {
              city: {
                S: 'Warsaw'
              },
              details: {
                M: {
                  street: {
                    S: 'Avenue'
                  },
                  num: {
                    N: '123'
                  },
                  clientIds: {
                    SS: ['12', '123', '345']
                  }
                }
              },
              locations: {
                L: [
                  {
                    M: {
                      city: {
                        S: 'Wro'
                      }
                    }
                  },
                  {
                    M: {
                      city: {
                        S: 'Wro2'
                      }
                    }
                  }
                ]
              }
            }
          },
          id: {
            S: '12'
          },
          list: {
            L: [
              {
                B: 'dGVzdCE='
              }
            ]
          }
        },
        OldImage: {
          number: {
            N: '123'
          },
          nbset: {
            NS: ['12']
          },
          data: {
            M: {
              '12': {
                BS: ['YWRzYQ==', 'dGVzdCE=']
              },
              first: {
                S: 'first'
              }
            }
          },
          strset: {
            SS: ['asd', 'asdasd']
          },
          id: {
            S: '12'
          },
          list: {
            L: [
              {
                B: 'dGVzdCE='
              }
            ]
          }
        },
        SequenceNumber: '11844300000000003688488011',
        SizeBytes: 267,
        StreamViewType: 'NEW_AND_OLD_IMAGES'
      },
      eventSourceARN:
        'arn:aws:dynamodb:eu-central-1:746924096579:table/test/stream/2019-01-26T14:35:08.985'
    }
  ]
}
```
If your code applied then we get this from elasticsearch:
```
{ number: 123, nbset: [12], strset: ['asd', 'asdasd'], id: '12' }
```
If no change:
```
{
  number: 123,
  nbset: { wrapperName: 'Set', values: [12], type: 'Number' },
  data: {
    '12': {
      wrapperName: 'Set',
      values: [
        { type: 'Buffer', data: [89, 87, 82, 122, 89, 81, 61, 61] },
        { type: 'Buffer', data: [100, 71, 86, 122, 100, 67, 69, 61] }
      ],
      type: 'Binary'
    },
    first: 'first'
  },
  strset: { wrapperName: 'Set', values: ['asd', 'asdasd'], type: 'String' },
  id: '112',
  list: [{ type: 'Buffer', data: [100, 71, 86, 122, 100, 67, 69, 61] }]
}
```
At this point it is better to leave it as it is. I agree that we should consider pushing plain object. I would love to see it working, here.

**Comment by alecdotico** [comment]
Actually this solution works for me in my custom code version, saving inner objects in Elasticsearch documents. As you can see in the documentation, a DynamoDB Record with Map data types contain the stringified version of it, so not exactly as your example. `Type: String to AttributeValue object map `
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_AttributeValue.html

**Comment by matrus2** [comment]
@alecdotico I took my data directly from a real world example. The first is a log from CloudWatch emitted by AWS Lambda on INSERT event. That is why I don't get this part `As you can see in the documentation, a DynamoDB Record with Map data types contain the stringified version of it, so not exactly as your example.`. If you can give more details, it would be helpful.

**Comment by alecdotico** [comment]
I see the issue now. I am using Dynamoose, which [according to documentation](https://dynamoosejs.com/api#attribute-types) it is storing inner objects as Maps by default, but in reality they are saved as strings. That's why my Dynamo Records had a String instead of a Map.

**Pull request closed without merging**
