### PR TITLE
tests passing; feature done: es batch

### PR DESCRIPTION
**Pull request by aterreno**
Hi @matrus2 first of all thanks for the awesome library, I've been using this pattern for a couple of years, and two years ago either this lib wasn't around or I didn't find it so we built out own solution. 

But right now we are using it in production with good results. 

I thought about implementing the ES BATCH inserts, as we have a lot of data. 

The changes are pretty simple, it just took me forever to figure out the rather awkward API of elasticsearch.js for this.  (see also this discussion https://github.com/elastic/elasticsearch-js/issues/1200) 

One thing to note is that it will always refresh now, but it's only one refresh per batch. 

Tests are passing, let me know if you like it or you want to change anything else. 

Thanks & Keep the good work! 

Antonio

### CODE REVIEW

**Comment by aterreno** [comment]
Just noticed that the build fails on CI but it passes fine on my machine. 
I wonder if it's a version of ES problem? 

Really weird, using docker as suggested from the code.

**Comment by matrus2** [comment]
Hi, Thx for the PR. Will check asap.

**Comment by aterreno** [comment]
@matrus2 any feedback? or do you know why the tests are not passing? I'd like to have this meged and start using it on our systems. thanks

**Comment by matrus2** [comment]
Hi,
Probably reason why tests fail is that Travis uses 5.5.0 version of es. You can try to set the more recent version as they specify here (or leave it for me after approval I will set it)

https://docs.travis-ci.com/user/database-setup/#installing-specific-versions-of-elasticsearch

One think I would change is to add a feature flag to the options eg. `useBulk` by default set to false. I suggest also to rely on refresh flag from options. Some people might not like that every bulk insert forces refresh.

Thx

**Comment by aterreno** [comment]
Nice, build now passing with ES 7.7.1. 

I'll try to add the switch

**Comment by aterreno** [comment]
allright @matrus2 all done. 
- Refresh honored in bulk, default is back to false also for nonBulk option
- Boolean option useBulk, defaulted to false
- Tests passing on ES 7.7.1

The only thing missing now is tests for bulk. One nasty option would be to duplicate them all and pass useBulk=true. 

Otherwise, I can copy the multiple events test and that should be good enough for coverage, what do you think?

**Comment by aterreno** [comment]
@matrus2 I've done the last option, let me know if you are happy with this, thanks

**Pull request merged**
